esphome:
  name: phaseconmon

esp32:
  board: wt32-eth01
  framework:
    type: esp-idf

#  Can't do wiFi and Ethernet
# wifi:
#   networks:
#   - ssid: !secret farm_wifi_ssid
#       password: !secret farm_wifi_pw
#     - ssid: !secret _218_wifi_ssid
#       password: !secret _218_wifi_pw
#   # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "PhaseconmonFallback"
#     password: !secret fallback_ap_pw
# # Captive portal to be able to set the WiFi PW back (requires wifi and AP)
# captive_portal:

# Debug sensor like in https://esphome.io/components/debug.html
debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    # fragmentation: Only on ESP8266
    #   name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    # psram:
    #   name: "Free PSRAM"
    cpu_frequency:
      name: "CPU Frequency"

  # - platform: adc
  #   pin: GPIO36 # Solder GPIO36 to 3V3 pin to measure VCC
  #   name: "VCC Voltage"
  #   attenuation: 12db

  - platform: internal_temperature
    name: "MCU Temperature"

# Logger must be at least debug (default)
logger:
  level: debug
  baud_rate: 0 # disable UART output

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

# Device Specific Config
#WT32-ETH01 ethernet: https://esphome.io/components/ethernet.html
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

binary_sensor:
  - platform: status
    # Status for helping see if it is online
    name: "Barritt NE Phase Converter Status"

  # Sense the optocoupler pulling low when on
  - platform: gpio
    pin:
      number: GPIO39 # GPIO39
      inverted: true
      mode:
        input: true
        # We don't need a pullup, HW has a 4.7k pullup and GPIO34-39 don't have pullups
    name: "Barritt NE Phase Converter Running"
    device_class: power
    filters:
      - delayed_on: 300ms
      - delayed_off: 1000ms

# Two relay channels, momentary buttons https://esphome.io/components/button/
switch:
  - platform: gpio
    # Press and release to turn Phase Converter on
    name: "Relay Start Phase Converter"
    id: relayStartPhaseCon
    pin:
      number: GPIO33 # labeled 485_EN on WT32-ETH01
      inverted: true
      mode:
        output: true
        open_drain: true
    icon: "mdi:electric-switch-closed"
    on_turn_on:
      - delay: 350ms
      - switch.turn_off: relayStartPhaseCon

  - platform: gpio
    # Press and release to turn phase converter off
    name: "Relay Stop Phase Converter"
    id: relayStopPhaseCon
    pin:
      number: GPIO32 # labeled CFG on WT32-ETH01
      inverted: true
      mode:
        output: true
        open_drain: true
    icon: "mdi:electric-switch-open"
    on_turn_on:
      - delay: 350ms
      - switch.turn_off: relayStopPhaseCon

  - platform: gpio
    # Press and release to turn Phase Converter on
    name: "SSR Start Phase Converter"
    id: ssrStartPhaseCon
    pin:
      number: GPIO15 # labeled IO15
      inverted: false
      mode:
        output: true
        open_drain: false
    icon: "mdi:electric-switch-closed"
    on_turn_on:
      - delay: 350ms
      - switch.turn_off: ssrStartPhaseCon

  - platform: gpio
    # Press and release to turn phase converter off
    name: "SSR Stop Phase Converter"
    id: ssrStopPhaseCon
    pin:
      number: GPIO14 # labeled IO14
      inverted: false
      mode:
        output: true
        open_drain: false
    icon: "mdi:electric-switch-open"
    on_turn_on:
      - delay: 350ms
      - switch.turn_off: ssrStopPhaseCon

